apiVersion: v1
kind: ConfigMap
metadata:
  name: galen-integration-config
  namespace: galen-integration
  labels:
    app: galen-integration
data:
  BlobContainerName: "inbound"
  RecordRepository__CommandTimeoutSeconds: "120"
